### ISSUE TITLE
Criação da aba News e inserção do livro do Fred na aba publications 

### ISSUE THREAD

**Issue by ViniciusMenez** [atoms-ufrj/atoms_site#22]
Oi Charlles.

Acabei de fazer algumas atualizações no site do ATOMS. Existem 2 pontos que gostaria de perguntar:

1 - Eu e o Iuri adicionamos a Aba "News". Só que para adicioná-la, tivemos que alterar o arquivo "layout.xml". Acontece que no início deste arquivo tem a seguinte mensagem: "Generated by doxygen 1.8.11", e quando compilamos todo o projeto aqui, este arquivo não sofre alterações, ou seja, o nosso doxygen não está compilanto ele novamente. Gostariamos de saber se o que fizemos está correto, se a gente podia mesmo alterar o arquivo "layout.xml".

2 - A gente adicionou o livro do Fred na aba News, mas também gostariamos de adicioná-lo na Aba Publications. Acontece que o livro do Fred não possui DOI, somente ISBN, e o programa não reconhece o ISBN. Nós descobrimos que cada capítulo do livro tem seu DOI, mas não seria legal colocar a referência de cada capítulo na Aba Publications. Então eu e o Iuri tivemos a ideia de pegar o DOI da página "Front Matter" do livro (http://www.sciencedirect.com/science/article/pii/B9780128124529000095) e adicionar na Aba Publications. Acontece que a página Front Matter não possui os autores, então acaba dando erro na hora da compilação. Diante disso, nós conseguimos um artifício aqui que possibilitou a inclusão da referência do livro do Fred, que foi o seguinte: nós incluímos diretamente no arquivo "publications.html"  o seguinte texto no final da lista de referências :

@book{2017,
    doi = {10.1016/b978-0-12-812452-9.00009-5},
    url = {https://doi.org/10.1016%2Fb978-0-12-812452-9.00009-5},
    year = 2017,
    publisher = {Elsevier},
    pages = {i--iii},
    author = {Rog{\'{e}}rio Oliveira Esp{\'{o}}sito and Pedro Henrique Rodrigues Alij{\'{o}} and Jos{\'{e}} Antonio Scilipoti and Frederico Wanderley Tavares},
    title = {Compositional Grading in Oil and Gas Reservoirs},
    booktitle = {Compositional Grading in Oil and Gas Reservoirs}
}

Desta maneira, a referência do livro apareceu perfeitamente na Aba Publications. O Porém é que toda vez que as rotinas forem compiladas, estre trecho será excluído, tendo que ser adicionado manualmente sempre após cada compilação. Gostaríamos de saber se não tem como alterar a parte do código que compila o porgrama, de forma que o texto acima seja sempre adcionado ao final da lista de publicações no arquivo "publications.html".  O trecho copiado acima foi adionado ao projeto no git hub, na seguinte pasta: pages/more_publications/esposito-et-al-2017.md. Essa parte da referência do Fred foi apenas uma ideia mesmo, se não for factível, não tem problema.

Muito obrigado Charlles e qualquer dúvida é só falar.

Abraço
Vinicius

**Comment by craabreu** [comment]
@ViniciusMenez Só agora eu vi esse issue. Acho que uma solução seria adicionar um arquivo contendo entradas na forma de bibtex e simplesmente fazer com que o script concatene esse arquivo com a saída do processamento dos DOI's.

**Comment by craabreu** [comment]
@ViniciusMenez  Aproveitei para passar a maior parte das referências (pré-2018) para o arquivo publications.bib, que se torna permanente. Assim, podemos também aproveitar para corrigir problemas de acentuação.
